flags = "-Wall -g -std=gnu11"
env = Environment(CC = "gcc", CCFLAGS = flags)
src = [
    "main.c",
    "ui.c",
    "misc.c",
    "uitex.c",
    "oglTools.c",
    "fileTools.c",
    "timestamp.c",
    "error.c"
]
env.Program("GraphPunk", src, LIBS = ["GL", "GLEW", "SDL2", "m"])
