#define uitex_path "img/uitex.bmp"
#define uitex_size_x  512.0f
#define uitex_size_y  512.0f

#define uitex_ibord_tl_x   1.0f/uitex_size_x
#define uitex_ibord_tl_y  34.0f/uitex_size_y
#define uitex_ibord_tr_x   2.0f/uitex_size_x
#define uitex_ibord_tr_y  34.0f/uitex_size_y
#define uitex_ibord_br_x   2.0f/uitex_size_x
#define uitex_ibord_br_y  33.0f/uitex_size_y
#define uitex_ibord_bl_x   1.0f/uitex_size_x
#define uitex_ibord_bl_y  33.0f/uitex_size_y
#define uitex_obord_tl_x   0.0f
#define uitex_obord_tl_y  35.0f/uitex_size_y
#define uitex_obord_tr_x   3.0f/uitex_size_x
#define uitex_obord_tr_y  35.0f/uitex_size_y
#define uitex_obord_br_x   3.0f/uitex_size_x
#define uitex_obord_br_y  32.0f/uitex_size_y
#define uitex_obord_bl_x   0.0f
#define uitex_obord_bl_y  32.0f/uitex_size_y
#define uitex_cntr_tl_x    0.0f
#define uitex_cntr_tl_y   32.0f/uitex_size_y
#define uitex_cntr_tr_x   32.0f/uitex_size_x
#define uitex_cntr_tr_y   32.0f/uitex_size_y
#define uitex_cntr_br_x   32.0f/uitex_size_x
#define uitex_cntr_br_y    0.0f
#define uitex_cntr_bl_x    0.0f
#define uitex_cntr_bl_y    0.0f
